In [266]:
import pandas as pd
import re
df = pd.read_csv("nsw-property-sales-data-updated20260910.csv", low_memory=False)

In [267]:
df.head(10)

,District code,Property ID,Valuation number,Sale counter,Download date / time,Property name,Property unit number,Property house number,Property street name,Property locality,...,Strata lot number,Component code,Sale code,% Interest of sale,Dealing number,Parcels in sale,Property legal description,Part interest flag,Non-market price flag,Date error flag
0,4,109747.0,NaN,5,2019-01-07 01:09:00,NaN,NaN,5,Columbia Cl,Woodrising,...,NaN,AFB,NaN,NaN,AN973262,1,3021/802535,False,False,False
1,4,110548.0,NaN,4,2019-01-07 01:09:00,NaN,NaN,23,Southern Cross Dr,Woodrising,...,NaN,AFB,NaN,NaN,AN967990,1,2097/717154,False,False,False
2,4,135349.0,NaN,6,2019-01-07 01:09:00,NaN,NaN,11,George St,Highfields,...,NaN,AEG,NaN,NaN,AN972260,1,2/800348,False,False,False
3,4,139881.0,NaN,7,2019-01-07 01:09:00,NaN,NaN,57,Scenic Dr,Caves Beach,...,NaN,AKA,NaN,NaN,AN971724,1,305/227234,False,False,False
4,4,156934.0,NaN,8,2019-01-07 01:09:00,NaN,NaN,54,Andrew Rd,Valentine,...,NaN,AGJ,NaN,33.0,AN976618,1,433/505515,True,False,False
5,4,156934.0,NaN,9,2019-01-07 01:09:00,NaN,NaN,54,Andrew Rd,Valentine,...,NaN,AGJ,NaN,33.0,AN976619,1,433/505515,True,False,False
6,4,161585.0,NaN,10,2019-01-07 01:09:00,NaN,NaN,5,Haynes Ave,Eleebana,...,NaN,AGA,NaN,NaN,AN978630,1,23/220217,False,False,False
7,5,176159.0,NaN,4,2019-01-07 01:09:00,NaN,NaN,4,Clyde St,Rutherford,...,NaN,AAU,NaN,NaN,AN974407,1,79/235661,False,False,False
8,1,19614.0,NaN,3,2019-01-07 01:09:00,Cypress Lakes Resort,505,15,Thompsons Rd,Pokolbin,...,5.0,NaN,NaN,NaN,AN972670,1,5/SP53418,False,False,False
9,8,211431.0,NaN,7,2019-01-07 01:09:00,NaN,NaN,35,Catherine St,Waratah West,...,NaN,AJP,NaN,NaN,AN965561,1,49/19890,False,False,False

In [268]:
df.columns

Index(['District code', 'Property ID', 'Valuation number', 'Sale counter',
       'Download date / time', 'Property name', 'Property unit number',
       'Property house number', 'Property street name', 'Property locality',
       'Property post code', 'Area (m2)', 'Area (source)',
       'Area type (source)', 'Dimensions', 'Contract date', 'Settlement date',
       'Purchase price', 'Zoning', 'Nature of property',
       'Nature of property (description)', 'Primary purpose',
       'Primary purpose (normalised)', 'Strata lot number', 'Component code',
       'Sale code', '% Interest of sale', 'Dealing number', 'Parcels in sale',
       'Property legal description', 'Part interest flag',
       'Non-market price flag', 'Date error flag'],
      dtype='object')

In [269]:
# Drop Sale counter since its not needed for our business case
# Contract Dates might have errors in it so use Dealing number to identify Sale contract
# Purchase price is not always the whole property price and might include properties that have stakes in the properties
# so we will eliminate all the properties that have part interest flag since we only want properties that get us 100% ownership
# There might be rows with multiple same price values caused due to Parcels in sale column so we will try to get only 1 row from them
# in order to maintain consistency, we can do df['Parcels in sale']=1 or group by Dealing number
# drop zoning since we wont need that for our use case
# drop the rows where Non-market price flag is set since they are all family transfers or having sale price less than 1000$
# which is not true market value

# Columns to be dropped that wont be needed for our use case

# Sale counter, Download date/time, Property name, Area (source), Area type (source), Dimensions, 
# Zoning, Nature of property, Primary purpose, Component Code, Sale code, Property legal description,  Strata lot number

df = df.drop(['Sale counter', 'Download date / time', 'Property name', 'Area (source)', 'Area type (source)',
                     'Dimensions', 'Zoning', 'Nature of property', 'Primary purpose', 'Component code', 'Valuation number', 'Sale code', 'Strata lot number', 'Property legal description'], axis=1)

In [270]:
df.head(3)

,District code,Property ID,Property unit number,Property house number,Property street name,Property locality,Property post code,Area (m2),Contract date,Settlement date,Purchase price,Nature of property (description),Primary purpose (normalised),% Interest of sale,Dealing number,Parcels in sale,Part interest flag,Non-market price flag,Date error flag
0,4,109747.0,NaN,5,Columbia Cl,Woodrising,2284.0,800.0,2018-12-04,2018-12-28,437000,Residence,Residence,NaN,AN973262,1,False,False,False
1,4,110548.0,NaN,23,Southern Cross Dr,Woodrising,2284.0,719.3,2018-09-27,2018-12-11,438000,Residence,Residence,NaN,AN967990,1,False,False,False
2,4,135349.0,NaN,11,George St,Highfields,2289.0,688.8,2018-11-05,2018-12-17,514000,Residence,Residence,NaN,AN972260,1,False,False,False

In [271]:
df.columns

Index(['District code', 'Property ID', 'Property unit number',
       'Property house number', 'Property street name', 'Property locality',
       'Property post code', 'Area (m2)', 'Contract date', 'Settlement date',
       'Purchase price', 'Nature of property (description)',
       'Primary purpose (normalised)', '% Interest of sale', 'Dealing number',
       'Parcels in sale', 'Part interest flag', 'Non-market price flag',
       'Date error flag'],
      dtype='object')

In [272]:


# Clean and transform the column names
df.columns = (df.columns
              .str.replace('%', 'percent', regex=False)        # Convert % to text
              .str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)  # Remove brackets and symbols
              .str.replace(r'\s+', '_', regex=True)            # Change spaces to underscores
              .str.lower()                                     # Convert to lowercase
              .str.strip('_'))                                 # Remove any trailing underscores

In [273]:
df.columns

Index(['district_code', 'property_id', 'property_unit_number',
       'property_house_number', 'property_street_name', 'property_locality',
       'property_post_code', 'area_m2', 'contract_date', 'settlement_date',
       'purchase_price', 'nature_of_property_description',
       'primary_purpose_normalised', 'percent_interest_of_sale',
       'dealing_number', 'parcels_in_sale', 'part_interest_flag',
       'nonmarket_price_flag', 'date_error_flag'],
      dtype='object')

In [274]:
df['parcels_in_sale'].describe()

count    1.508054e+06
mean     1.167657e+00
std      2.189878e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.200000e+02
Name: parcels_in_sale, dtype: float64

In [275]:
df['parcels_in_sale'].isna().sum()

np.int64(0)

In [276]:
df['parcels_in_sale'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1508054 entries, 0 to 1508053
Series name: parcels_in_sale
Non-Null Count    Dtype
--------------    -----
1508054 non-null  int64
dtypes: int64(1)
memory usage: 11.5 MB

In [277]:
df.describe()

,district_code,property_id,property_post_code,area_m2,purchase_price,percent_interest_of_sale,parcels_in_sale
count,1.508054e+06,1.507902e+06,1.507027e+06,1.187541e+06,1.508054e+06,5374.000000,1.508054e+06
mean,2.194654e+02,2.606699e+06,2.357207e+03,1.496091e+05,1.411374e+06,42.093041,1.167657e+00
std,1.650161e+02,1.519172e+06,2.500792e+02,5.316527e+06,8.022246e+06,17.461491,2.189878e+00
min,1.000000e+00,2.000000e+00,2.000000e+03,0.000000e+00,1.000000e+02,1.000000,1.000000e+00
25%,1.010000e+02,1.254412e+06,2.147000e+03,3.216000e+02,5.250000e+05,33.000000,1.000000e+00
50%,2.170000e+02,2.602490e+06,2.295000e+03,6.000000e+02,7.875000e+05,50.000000,1.000000e+00
75%,2.610000e+02,4.141534e+06,2.558000e+03,8.870000e+02,1.267000e+06,50.000000,1.000000e+00
max,9.020000e+02,6.074593e+06,4.385000e+03,2.703300e+09,8.950000e+08,99.000000,1.200000e+02

In [278]:
df['part_interest_flag'].describe()

count     1508054
unique          2
top         False
freq      1502680
Name: part_interest_flag, dtype: object

In [279]:
df['part_interest_flag'].isna().sum()

np.int64(0)

In [280]:
df['nonmarket_price_flag'].describe()

count     1508054
unique          2
top         False
freq      1507367
Name: nonmarket_price_flag, dtype: object

In [281]:
df['nonmarket_price_flag'].isna().sum()

np.int64(0)

In [282]:
df['date_error_flag'].describe()

count     1508054
unique          2
top         False
freq      1508051
Name: date_error_flag, dtype: object

In [283]:
df['date_error_flag'].isna().sum()

np.int64(0)

In [284]:
# Converting these objects to their respective data types so we can get rid of the duplicates and unneeded data for our use case
# Convert parcels_in_sale to numbers, turning invalid text into NaN (Missing Values)
df['parcels_in_sale'] = pd.to_numeric(df['parcels_in_sale'], errors='coerce')

# Convert the part_interest_flag, nonmarket_price_flag and date_error_flag to boolean
df = df.astype({'part_interest_flag': 'bool',
       'nonmarket_price_flag':'bool', 'date_error_flag':'bool'})

In [285]:
# Get only the rows that have one parcel since multiple parcels would show us multiple instances of the same price for the same sale
df = df[df['parcels_in_sale']==1]

In [286]:
df.columns

Index(['district_code', 'property_id', 'property_unit_number',
       'property_house_number', 'property_street_name', 'property_locality',
       'property_post_code', 'area_m2', 'contract_date', 'settlement_date',
       'purchase_price', 'nature_of_property_description',
       'primary_purpose_normalised', 'percent_interest_of_sale',
       'dealing_number', 'parcels_in_sale', 'part_interest_flag',
       'nonmarket_price_flag', 'date_error_flag'],
      dtype='object')

In [287]:
# Also we will be eliminating the rows where the transfers have prices less that 1000$ since they might be family transfers
# and do not hold actual market value
df = df[df['nonmarket_price_flag'] == False]

# Here we will be getting rid of the properties that have shared ownership since we want 100% ownership for the property
df = df[df['part_interest_flag'] == False]

In [288]:
# Drop these columns since they are not needed now
df = df.drop(columns = ['nonmarket_price_flag', 'part_interest_flag', 'parcels_in_sale', 'percent_interest_of_sale'])

In [289]:
df.head()

,district_code,property_id,property_unit_number,property_house_number,property_street_name,property_locality,property_post_code,area_m2,contract_date,settlement_date,purchase_price,nature_of_property_description,primary_purpose_normalised,dealing_number,date_error_flag
0,4,109747.0,NaN,5,Columbia Cl,Woodrising,2284.0,800.0,2018-12-04,2018-12-28,437000,Residence,Residence,AN973262,False
1,4,110548.0,NaN,23,Southern Cross Dr,Woodrising,2284.0,719.3,2018-09-27,2018-12-11,438000,Residence,Residence,AN967990,False
2,4,135349.0,NaN,11,George St,Highfields,2289.0,688.8,2018-11-05,2018-12-17,514000,Residence,Residence,AN972260,False
3,4,139881.0,NaN,57,Scenic Dr,Caves Beach,2281.0,689.2,2018-11-11,2018-12-17,910000,Residence,Residence,AN971724,False
6,4,161585.0,NaN,5,Haynes Ave,Eleebana,2282.0,619.7,2018-10-31,2019-01-03,889000,Residence,Residence,AN978630,False

In [290]:
df['property_id'].describe()

count    1.439784e+06
mean     2.611302e+06
std      1.525825e+06
min      2.000000e+00
25%      1.242552e+06
50%      2.615064e+06
75%      4.150246e+06
max      6.074593e+06
Name: property_id, dtype: float64

In [291]:
df['property_id'].isna().sum()

np.int64(119)

In [292]:
# dropping all the rows where property id is null
mask = df['property_id'].isnull()


df = df.drop(
    df.loc[mask].index
)

In [293]:
df.loc[mask,:]

Empty DataFrame
Columns: [district_code, property_id, property_unit_number, property_house_number, property_street_name, property_locality, property_post_code, area_m2, contract_date, settlement_date, purchase_price, nature_of_property_description, primary_purpose_normalised, dealing_number, date_error_flag]
Index: []

In [294]:
df["property_id"].isnull().sum()

np.int64(0)

In [295]:
# same locality should have the same postcode so we can map these into the data
df['property_post_code'].isnull().sum()

np.int64(932)

In [296]:
# 1. Create a clean mapping dictionary from valid rows
# Drops rows where postcode or locality is missing, then drops duplicate localities
postcode_map = (
    df.dropna(subset=["property_locality", "property_post_code"])
    .drop_duplicates(subset=["property_locality"])
    .set_index("property_locality")["property_post_code"]
    .to_dict()
)

# 2. Fill the missing postcodes using the map
df["property_post_code"] = df["property_post_code"].fillna(df["property_locality"].map(postcode_map))

# 3. Optional: Convert postcode to float64
df["property_post_code"] = df["property_post_code"].astype("float64")

In [297]:
df['property_post_code'].isnull().sum()
# Successfully dropped the number of missing postcodes from 932 to 15

np.int64(15)

In [298]:
df.loc[df['property_post_code'].isna(),:]
# These properties have no name or any information related to the property so lets eliminate data like this

,district_code,property_id,property_unit_number,property_house_number,property_street_name,property_locality,property_post_code,area_m2,contract_date,settlement_date,purchase_price,nature_of_property_description,primary_purpose_normalised,dealing_number,date_error_flag
1282295,210,6005920.0,NaN,NaN,NaN,NaN,NaN,0.0,2022-03-25,2025-07-22,11000000,Residence,Residence,AV262012,False
1282296,210,6005920.0,NaN,NaN,NaN,NaN,NaN,0.0,2022-06-10,2025-07-24,6750000,Residence,Residence,AV271191,False
1282297,210,6005920.0,NaN,NaN,NaN,NaN,NaN,0.0,2022-05-13,2025-08-07,8000000,Residence,Residence,AV312439,False
1325767,210,6005920.0,NaN,NaN,NaN,NaN,NaN,0.0,2022-05-31,2025-09-22,6550000,Residence,Residence,AV444795,False
1504451,1,6066352.0,NaN,NaN,NaN,NaN,NaN,0.0,2026-07-24,2026-08-14,364000,Vacant land,Vacant land,AW375609,False
1506318,217,6043899.0,NaN,NaN,NaN,NaN,NaN,352.5,2025-02-03,2026-03-17,632900,Residence,Residence,AV951415,False
1506333,217,6043943.0,NaN,NaN,NaN,NaN,NaN,288.1,2025-05-20,2026-03-17,576900,Residence,Residence,AV951098,False
1506334,217,6043948.0,NaN,NaN,NaN,NaN,NaN,252.0,2025-05-16,2026-03-20,503900,Residence,Residence,AV965692,False
1506840,223,6070859.0,NaN,NaN,NaN,NaN,NaN,0.0,2026-03-11,2026-08-19,740000,Vacant land,Vacant land,AW387448,False
1506841,223,6070861.0,NaN,NaN,NaN,NaN,NaN,0.0,2026-03-05,2026-08-19,730000,Vacant land,Vacant land,AW387335,False
1506842,223,6070863.0,NaN,NaN,NaN,NaN,NaN,0.0,2026-05-15,2026-08-19,730000,Vacant land,Vacant land,AW387434,False
1506843,223,6070865.0,NaN,NaN,NaN,NaN,NaN,0.0,2026-07-10,2026-08-19,690000,Vacant land,Vacant land,AW387340,False
1506844,223,6070866.0,NaN,NaN,NaN,NaN,NaN,0.0,2026-01-20,2026-08-19,700000,Vacant land,Vacant land,AW387422,False
1506845,223,6070870.0,NaN,NaN,NaN,NaN,NaN,0.0,2026-03-30,2026-08-19,740000,Vacant land,Vacant land,AW387374,False
1506846,223,6070872.0,NaN,NaN,NaN,NaN,NaN,0.0,2026-05-11,2026-08-19,730000,Vacant land,Vacant land,AW387390,False

In [299]:
# would drop the columns if these identifiers are not present
# List of columns to check
target_cols = [
    "property_post_code",
    "property_locality",
    "property_street_name",
    "property_house_number"
]

# Drop rows only if these columns are NaN
for col in target_cols:
    df = df.dropna(subset=[col])

In [300]:
df.loc[df['property_post_code'].isna(),:]

Empty DataFrame
Columns: [district_code, property_id, property_unit_number, property_house_number, property_street_name, property_locality, property_post_code, area_m2, contract_date, settlement_date, purchase_price, nature_of_property_description, primary_purpose_normalised, dealing_number, date_error_flag]
Index: []

In [301]:
# Changing all the property location variables to string
df['property_unit_number'] = df['property_unit_number'].astype('string')
df['property_house_number'] = df['property_house_number'].astype('string')
df['property_street_name'] = df['property_street_name'].astype('string')
df['property_locality'] = df['property_locality'].astype('string')

In [302]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1416598 entries, 0 to 1508051
Data columns (total 15 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   district_code                   1416598 non-null  int64
 1   property_id                     1416598 non-null  float64
 2   property_unit_number            453318 non-null   string
 3   property_house_number           1416598 non-null  string
 4   property_street_name            1416598 non-null  string
 5   property_locality               1416598 non-null  string
 6   property_post_code              1416598 non-null  float64
 7   area_m2                         1128158 non-null  float64
 8   contract_date                   1416290 non-null  object
 9   settlement_date                 1416577 non-null  object
 10  purchase_price                  1416598 non-null  int64
 11  nature_of_property_description  1416598 non-null  object
 12  primary_purpose_normalised      1416441 non-null  object
 13  dealing_number                  1416598 non-null  object
 14  date_error_flag                 1416598 non-null  bool
dtypes: bool(1), float64(3), int64(2), object(5), string(4)
memory usage: 163.5+ MB

In [303]:
df['district_code'] = df['district_code'].astype('string').str.zfill(3)

In [304]:
df['district_code'].value_counts()

district_code
214    68065
259    61862
708    47794
260    45696
258    41106
       ...
134       47
024       10
058        6
062        4
069        4
Name: count, Length: 144, dtype: Int64

In [305]:
# We have the Council code but dont have the Council that it maps to so we shall do the mapping ourselves

council_code_map = {
    "001": "Cessnock", "118": "Blayney", "240": "Gilgandra",
    "002": "Dungog", "123": "Oberon", "243": "Hay",
    "004": "Lake Macquarie", "124": "Orange", "244": "Lachlan",
    "005": "Maitland", "137": "Burwood", "247": "Narrabri",
    "007": "Muswellbrook", "139": "Canada Bay", "250": "Tenterfield",
    "008": "Newcastle", "143": "Strathfield", "251": "Narromine",
    "010": "Port Stephens", "144": "Sutherland", "252": "Walcha",
    "012": "Singleton", "148": "Ballina", "253": "Walgett",
    "018": "Bega Valley", "149": "Bellingen", "254": "Warren",
    "042": "Cowra", "150": "Byron", "255": "Wentworth",
    "043": "Weddin", "151": "Richmond Valley", "257": "Armidale Regional",
    "050": "Albury", "152": "Coffs Harbour", "258": "Canterbury-Bankstown",
    "051": "Berrigan", "157": "Kempsey", "259": "Central Coast",
    "052": "Carrathool", "158": "Kyogle", "260": "City of Parramatta",
    "054": "Coolamon", "159": "Lismore", "261": "Cumberland",
    "061": "Junee", "164": "Nambucca", "262": "Edward River",
    "065": "Leeton", "171": "Tweed", "263": "Federation",
    "066": "Lockhart", "187": "Gunnedah", "264": "Georges River",
    "070": "Narrandera", "188": "Inverell", "265": "Cootamundra-Gundagai Regional",
    "074": "Griffith", "192": "Moree Plains", "266": "Hilltops",
    "081": "The Hills Shire", "199": "Uralla", "267": "Inner West",
    "082": "Hornsby", "207": "Randwick", "268": "Mid-Coast",
    "083": "Hunters Hill", "209": "Waverley", "269": "Murray River",
    "084": "Ku-ring-gai", "210": "Woollahra", "270": "Murrumbidgee",
    "085": "Lane Cove", "214": "Blacktown", "271": "Northern Beaches",
    "087": "Mosman", "216": "Blue Mountains", "272": "Queanbeyan-Palerang Regional",
    "088": "North Sydney", "217": "Camden", "273": "Snowy Monaro Regional",
    "089": "North Sydney", "218": "Campbelltown", "274": "Snowy Valleys", # Note: 088 / 089 are North Sydney
    "090": "Ryde", "219": "Hawkesbury", "275": "Dubbo Regional",
    "092": "Willoughby", "220": "Fairfield", "276": "Bayside",
    "097": "Eurobodalla", "222": "Lithgow", "300": "Gwydir",
    "098": "Kiama", "223": "Liverpool", "301": "Liverpool Plains",
    "100": "Shellharbour", "224": "Penrith", "302": "Glen Innes Severn",
    "101": "Shoalhaven", "226": "Wollondilly", "303": "Clarence Valley",
    "102": "Wingecarribee", "230": "Balranald", "511": "Upper Hunter",
    "103": "Wollongong", "231": "Bland", "526": "Upper Lachlan",
    "109": "Cabonne", "232": "Bogan", "528": "Yass Valley",
    "116": "Parkes", "233": "Brewarrina", "529": "Goulburn Mulwaree",
    "117": "Forbes", "234": "Broken Hill", "537": "Warrumbungle",
    "235": "Central Darling", "236": "Cobar", "538": "Temora",
    "238": "Coonamble", "239": "Bourke", "560": "Greater Hume",
    "575": "Wagga Wagga", "608": "Bathurst Regional", "620": "Mid Western Regional",
    "656": "Port Macquarie-Hastings", "666": "Tamworth Regional", "708": "City of Sydney",
    "902": "Unincorporated Area", "903": "Unincorporated Sydney Harbour"
}

# Map the codes to names into a new column
df["council_name"] = df["district_code"].map(council_code_map)

In [306]:
df["council_name"].value_counts(dropna=False)

council_name
Blacktown               68065
Central Coast           61862
City of Sydney          47794
City of Parramatta      45696
Canterbury-Bankstown    41106
                        ...
Bourke                    453
Balranald                 380
Central Darling           333
Brewarrina                191
Unincorporated Area        49
Name: count, Length: 130, dtype: int64

In [307]:
df["council_name"].isna().sum()
# Some codes dont have a council that we can map to

np.int64(1776)

In [308]:
df["district_code"].isna().sum()

np.int64(0)

In [309]:
df.loc[df["council_name"].isna(),:]

,district_code,property_id,property_unit_number,property_house_number,property_street_name,property_locality,property_post_code,area_m2,contract_date,settlement_date,purchase_price,nature_of_property_description,primary_purpose_normalised,dealing_number,date_error_flag,council_name
126,091,2884811.0,<NA>,40,Brighton St,Freshwater,2096.0,511.3,2018-10-25,2018-12-06,2600000,Residence,Residence,AN969287,False,NaN
153,091,4151551.0,16,697,Pittwater Rd,Dee Why,2099.0,81.0,2017-07-27,2018-12-20,760000,Residence,Residence,AN973521,False,NaN
154,091,4156733.0,<NA>,17,Howard Ave,Dee Why,2099.0,86.0,2018-05-17,2018-12-21,685000,Residence,Residence,AN970919,False,NaN
155,091,4156733.0,<NA>,17,Howard Ave,Dee Why,2099.0,84.0,2018-07-31,2018-12-20,695000,Residence,Residence,AN972178,False,NaN
156,091,4156733.0,<NA>,17,Howard Ave,Dee Why,2099.0,105.0,2018-05-28,2018-11-28,900000,Residence,Residence,AN904890,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20736,203,3101922.0,5,9,Myrtle St,Botany,2019.0,247.0,2018-12-13,2019-01-08,125000,Residence,Residence,AP75461,False,NaN
20753,203,3611543.0,12,1333,Botany Rd,Botany,2019.0,NaN,2019-02-15,2019-02-18,1000000,Residence,Residence,AP69544,False,NaN
20759,203,3740799.0,76,619,Gardeners Rd,Mascot,2020.0,86.0,2018-12-04,2019-01-31,660000,Residence,Residence,AP46826,False,NaN
20791,203,4093766.0,3006,50,Pemberton St,Botany,2019.0,NaN,2019-01-02,2019-02-14,588000,Residence,Residence,AP72724,False,NaN
20796,203,4102805.0,1501,128,Banks Ave,Eastgardens,2036.0,NaN,2018-12-10,2019-02-07,1044000,Residence,Residence,AP62226,False,NaN

In [310]:
# Filling unknown district codes with Unknown as the label also getting rid of the disctrict code column since its redundant
df['council_name']= df['council_name'].fillna("Unknown").astype('string')
df = df.drop(columns=['district_code'])

In [311]:
df['council_name'].isna().sum()

np.int64(0)

In [312]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1416598 entries, 0 to 1508051
Data columns (total 15 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   property_id                     1416598 non-null  float64
 1   property_unit_number            453318 non-null   string
 2   property_house_number           1416598 non-null  string
 3   property_street_name            1416598 non-null  string
 4   property_locality               1416598 non-null  string
 5   property_post_code              1416598 non-null  float64
 6   area_m2                         1128158 non-null  float64
 7   contract_date                   1416290 non-null  object
 8   settlement_date                 1416577 non-null  object
 9   purchase_price                  1416598 non-null  int64
 10  nature_of_property_description  1416598 non-null  object
 11  primary_purpose_normalised      1416441 non-null  object
 12  dealing_number                  1416598 non-null  object
 13  date_error_flag                 1416598 non-null  bool
 14  council_name                    1416598 non-null  string
dtypes: bool(1), float64(3), int64(1), object(5), string(5)
memory usage: 163.5+ MB

In [313]:
# Convert the contract_date and settlement_date to the date datatype

df['contract_date'] = pd.to_datetime(df['contract_date'], errors="coerce")
df['settlement_date'] = pd.to_datetime(df['settlement_date'], errors="coerce")

# Eliminating the rows that have null on either of these columns
df = df.loc[~df['contract_date'].isna(), :]
df = df.loc[~df['settlement_date'].isna(), :]

In [314]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1416290 entries, 0 to 1508051
Data columns (total 15 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   property_id                     1416290 non-null  float64
 1   property_unit_number            453239 non-null   string
 2   property_house_number           1416290 non-null  string
 3   property_street_name            1416290 non-null  string
 4   property_locality               1416290 non-null  string
 5   property_post_code              1416290 non-null  float64
 6   area_m2                         1127897 non-null  float64
 7   contract_date                   1416290 non-null  datetime64[ns]
 8   settlement_date                 1416290 non-null  datetime64[ns]
 9   purchase_price                  1416290 non-null  int64
 10  nature_of_property_description  1416290 non-null  object
 11  primary_purpose_normalised      1416160 non-null  object
 12  dealing_number                  1416290 non-null  object
 13  date_error_flag                 1416290 non-null  bool
 14  council_name                    1416290 non-null  string
dtypes: bool(1), datetime64[ns](2), float64(3), int64(1), object(3), string(5)
memory usage: 163.4+ MB

In [315]:
# checking the dates where the contract_date is appearing after settlement_date
df['incorrect_dates'] = df['contract_date']>df['settlement_date']

In [316]:
#comparing it to the boolean already present in the table
(df['incorrect_dates'] == df['date_error_flag']).all()

np.True_

In [317]:
# We are going to assume that dates were misplaced and simply swap them for the ones that have incorrect_dates as True
# Create a boolean mask
mask = df['incorrect_dates']

# Use .loc with the mask to select rows, and swap the two columns
df.loc[mask, ['contract_date', 'settlement_date']] = df.loc[mask, ['settlement_date', 'contract_date']].values

In [318]:
# Recheck if we have date issues
df['incorrect_dates'] = df['contract_date']>df['settlement_date']

In [319]:
df['incorrect_dates'].all()==False

np.True_

In [320]:
# Now we can drop both the columns that were present to help the swap for dates
df = df.drop(columns=['incorrect_dates', 'date_error_flag'])

In [321]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1416290 entries, 0 to 1508051
Data columns (total 14 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   property_id                     1416290 non-null  float64
 1   property_unit_number            453239 non-null   string
 2   property_house_number           1416290 non-null  string
 3   property_street_name            1416290 non-null  string
 4   property_locality               1416290 non-null  string
 5   property_post_code              1416290 non-null  float64
 6   area_m2                         1127897 non-null  float64
 7   contract_date                   1416290 non-null  datetime64[ns]
 8   settlement_date                 1416290 non-null  datetime64[ns]
 9   purchase_price                  1416290 non-null  int64
 10  nature_of_property_description  1416290 non-null  object
 11  primary_purpose_normalised      1416160 non-null  object
 12  dealing_number                  1416290 non-null  object
 13  council_name                    1416290 non-null  string
dtypes: datetime64[ns](2), float64(3), int64(1), object(3), string(5)
memory usage: 162.1+ MB

In [322]:
# Need to get rid of outliers in purchase price and area_m2

# Checking area_m2 for nas
(df["area_m2"].astype(float) == 0).sum()

np.int64(1774)

In [323]:
# Replacing all the rows that have area_m2 as 0 with na
df["area_m2"] = df["area_m2"].replace(0, pd.NA)
df["area_m2"].isna().sum()

np.int64(290167)

In [324]:
# We will make a settlement year column in order to check outliers based on year and postcode
df['settlement_year'] = df['settlement_date'].dt.year
df.info()
df["area_m2"].isna().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 1416290 entries, 0 to 1508051
Data columns (total 15 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   property_id                     1416290 non-null  float64
 1   property_unit_number            453239 non-null   string
 2   property_house_number           1416290 non-null  string
 3   property_street_name            1416290 non-null  string
 4   property_locality               1416290 non-null  string
 5   property_post_code              1416290 non-null  float64
 6   area_m2                         1126123 non-null  object
 7   contract_date                   1416290 non-null  datetime64[ns]
 8   settlement_date                 1416290 non-null  datetime64[ns]
 9   purchase_price                  1416290 non-null  int64
 10  nature_of_property_description  1416290 non-null  object
 11  primary_purpose_normalised      1416160 non-null  object
 12  dealing_number                  1416290 non-null  object
 13  council_name                    1416290 non-null  string
 14  settlement_year                 1416290 non-null  int32
dtypes: datetime64[ns](2), float64(2), int32(1), int64(1), object(4), string(5)
memory usage: 167.5+ MB

np.int64(290167)

In [325]:
# IQR for purchase price by postcode + year
# Getting rid of the outliers so the data is fairly consistent and reliable based on purchase price
group_cols = ["property_post_code", "settlement_year"]

q1 = df.groupby(group_cols)["purchase_price"].transform(
    "quantile", 0.25
)

q3 = df.groupby(group_cols)["purchase_price"].transform(
    "quantile", 0.75
)

iqr = q3 - q1
k = 3
lower_bound = q1 - k * iqr
upper_bound = q3 + k * iqr

# Flag outliers
df["purchase_price_outlier"] = (
    (df["purchase_price"] < lower_bound) |
    (df["purchase_price"] > upper_bound)
)
# Check the outliers just in case we are throwing out useful information
#df.loc[df["purchase_price_outlier"], ['purchase_price', 'area_m2', 'property_post_code', 'settlement_year']].sort_values(
#    "purchase_price",
#    ascending=False
#)

df.loc[df['purchase_price_outlier'], ['purchase_price', 'area_m2', 'settlement_date', 'property_locality']].sort_values(by="purchase_price")

         purchase_price   area_m2 settlement_date property_locality
1166922            1000     626.2      2024-12-02      Erskine Park
916883             1000       NaN      2023-08-29   Wentworth Point
911317             1867       NaN      2023-08-18     Homebush West
877816             2500       NaN      2023-06-20   Berowra Heights
178119             3900       NaN      2019-12-20          St Marys
...                 ...       ...             ...               ...
94811         575000000   33050.0      2019-06-26           Burwood
546298        578500000    2944.0      2021-08-26            Sydney
1470744       590000000    1762.0      2026-06-10      North Sydney
1317352       830000000  110700.0      2025-06-23    Macquarie Park
715606        850000000    4041.0      2022-07-14            Sydney

[34116 rows x 4 columns]

In [326]:
# All the values seem legit so we wont be removing these rows
#df = df.loc[
#    ~df["purchase_price_outlier"], :
#    ]

In [327]:
print(df.loc[df['purchase_price_outlier']])

         property_id property_unit_number property_house_number  \
33         3697107.0                 <NA>                1245 A
116        1036071.0                 <NA>                    45
121        1048042.0                 <NA>                    14
122        1048070.0                 <NA>                    15
129        3258543.0                 <NA>                     5
...              ...                  ...                   ...
1507944    2731551.0                 <NA>                   103
1508038    6017060.0                  401                   2 A
1508044    6026252.0                    1                    29
1508045    6026252.0                    7                    29
1508046    6026252.0                    8                    29

        property_street_name property_locality  property_post_code    area_m2  \
33               Paterson Rd        Duns Creek              2321.0  1078600.0
116                 Crest Rd       Albion Park              2527.0      562.7
121               Samuel Cct       Albion Park              2527.0      527.6
122             Sandpiper Cl  Albion Park Rail              2527.0      561.8
129               Brecks Way     Pennant Hills              2120.0      738.8
...                      ...               ...                 ...        ...
1507944    Hastings River Dr    Port Macquarie              2444.0     4628.0
1508038            Gordon St    Port Macquarie              2444.0      406.0
1508044         Billyard Ave     Elizabeth Bay              2011.0      654.0
1508045         Billyard Ave     Elizabeth Bay              2011.0      451.0
1508046         Billyard Ave     Elizabeth Bay              2011.0      450.0

        contract_date settlement_date  purchase_price  \
33         2018-07-23      2018-08-20         3070000
116        2018-10-31      2018-12-14          565000
121        2018-11-23      2018-12-19          610000
122        2018-11-09      2018-12-14          565000
129        2018-11-22      2018-12-20         1250000
...               ...             ...             ...
1507944    2026-07-02      2026-08-17        12000000
1508038    2022-07-11      2025-12-19         3700000
1508044    2025-07-17      2025-12-05        17429995
1508045    2023-07-17      2025-12-05        20900000
1508046    2024-10-23      2025-12-10        23495000

        nature_of_property_description primary_purpose_normalised  \
33                               Other                      Rural
116                          Residence                  Residence
121                          Residence                  Residence
122                          Residence                  Residence
129                          Residence                  Residence
...                                ...                        ...
1507944                          Other                 Commercial
1508038                      Residence                  Residence
1508044                      Residence                  Residence
1508045                      Residence                  Residence
1508046                      Residence                  Residence

        dealing_number             council_name  settlement_year  \
33            AN864667            Port Stephens             2018
116           AN969577             Shellharbour             2018
121           AN970947             Shellharbour             2018
122           AN975976             Shellharbour             2018
129           AN974110                  Hornsby             2018
...                ...                      ...              ...
1507944       AW381329  Port Macquarie-Hastings             2026
1508038       AV743012  Port Macquarie-Hastings             2025
1508044       AV680815           City of Sydney             2025
1508045       AV680936           City of Sydney             2025
1508046       AV697180           City of Sydney             2025

         purchase_price_outlier
33                         True
116                        True
121                        True
122                        True
129                        True
...                         ...
1507944                    True
1508038                    True
1508044                    True
1508045                    True
1508046                    True

[34116 rows x 16 columns]

In [328]:
df['area_m2'].isna().sum()

np.int64(290167)

In [329]:
# 2920167 rows have no area_m2 which we will find using median price per m2 based of year and postcode
# which we will then divide it with purchase price where the area_m2 is na
# We will only keep area_m2 greater that 10 metre square for our dataset
df["price_per_m2"] = (
    df.loc[df["area_m2"]>10,"purchase_price"]/ df.loc[df["area_m2"]>10,"area_m2"]
)

median_price_per_m2 = (
    df.loc[df["area_m2"] > 10]  # <-- Only include areas higher than 10
    .groupby(["property_post_code", "settlement_year"])["price_per_m2"]
    .transform("median")
)

df["estimated_area_m2"] = (
    df["purchase_price"] / median_price_per_m2
)

df["area_m2"] = df["area_m2"].fillna(
    df["estimated_area_m2"]
)

/var/folders/kk/cjp9z4pn3llf4vb1pfnz3yxc0000gn/T/ipykernel_61080/3125569795.py:18: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["area_m2"] = df["area_m2"].fillna(

In [330]:
df.loc[df['area_m2'].isna(),:]
# These rows actually dont have any related data to how much the median pricing might be so we need to drop them
# This is just bad data

,property_id,property_unit_number,property_house_number,property_street_name,property_locality,property_post_code,area_m2,contract_date,settlement_date,purchase_price,nature_of_property_description,primary_purpose_normalised,dealing_number,council_name,settlement_year,purchase_price_outlier,price_per_m2,estimated_area_m2
8,19614.0,505,15,Thompsons Rd,Pokolbin,2320.0,NaN,2018-12-21,2018-12-28,265000,Residence,Residence,AN972670,Cessnock,2018,False,NaN,NaN
17,2825543.0,3,14,The Lane,Maryville,2293.0,NaN,2018-10-23,2018-11-20,910000,Other,Residence,AN921863,Newcastle,2018,False,NaN,NaN
18,283662.0,121,37,Horizons Dr,Salamander Bay,2317.0,NaN,2018-11-19,2018-12-20,268000,Residence,Residence,AN969072,Port Stephens,2018,False,NaN,NaN
21,3081387.0,101,15,Orara St,Waitara,2077.0,NaN,2018-11-27,2018-12-20,655000,Residence,Residence,AN974125,Hornsby,2018,False,NaN,NaN
22,3136388.0,2,58,Government Rd,Nelson Bay,2315.0,NaN,2018-11-07,2018-12-19,752500,Residence,Residence,AN971307,Port Stephens,2018,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1508019,4194471.0,2504,130,Elizabeth St,Sydney,2000.0,NaN,2026-07-08,2026-08-20,1160000,Residence,Residence,AW391547,City of Sydney,2026,False,NaN,NaN
1508020,4248200.0,258,24,Confectioners Way,Rosebery,2018.0,NaN,2026-07-21,2026-08-18,1055000,Residence,Residence,AW382718,City of Sydney,2026,False,NaN,NaN
1508041,6021876.0,18,11,Mission Tce,Lakewood,2443.0,NaN,2025-12-01,2025-12-22,565000,Residence,Residence,AV753703,Port Macquarie-Hastings,2025,False,NaN,NaN
1508042,6021876.0,23,11,Mission Tce,Lakewood,2443.0,NaN,2025-12-10,2025-12-22,540000,Residence,Residence,AV754887,Port Macquarie-Hastings,2025,False,NaN,NaN
1508043,6021876.0,10,11,Mission Tce,Lakewood,2443.0,NaN,2025-11-06,2025-11-28,559000,Residence,Residence,AV658562,Port Macquarie-Hastings,2025,False,NaN,NaN

In [331]:
df['area_m2'].isna().sum()

np.int64(290167)

In [332]:
# only 290167 rows left which have no area and we werent able to recover them either 
# so we can assume wont be useful for our insights and drop them
df = df.dropna(subset=["area_m2"])

In [333]:
df['area_m2'].isna().sum()

np.int64(0)

In [334]:
# Now we will keep a lower bound on area_m2 that is 10 metre square minimum as we discussed
# bug here is fixed
df = df.loc[df["area_m2"]>10,:]
df_sorted = df.sort_values(by="area_m2")
print(df_sorted)

         property_id property_unit_number property_house_number  \
525451     4381716.0                 <NA>                    17
118353      685583.0                 <NA>                    17
1176104    4590116.0                 <NA>                  48 B
795420     4156989.0                 <NA>                    65
167218     3950688.0                  430                   200
...              ...                  ...                   ...
753007     3753264.0                 <NA>                  5724
93594      3264546.0                 <NA>                 10463
533521     3425938.0                 <NA>                  2372
889020     3456648.0                 <NA>                  8147
865237     3491446.0                 <NA>                  8705

        property_street_name property_locality  property_post_code  \
525451            Turnock Dr      Cameron Park              2285.0
118353               Bass Pl           St Ives              2075.0
1176104               Day Rd        Cheltenham              2119.0
795420            Manning St             Kiama              2533.0
167218       The Entrance Rd             Erina              2250.0
...                      ...               ...                 ...
753007               Waka Rd        Tibooburra              2880.0
93594        Border Downs Rd        Milparinka              2880.0
533521      Henry Roberts Rd        Packsaddle              2880.0
889020      Hamilton Gate Rd         Wanaaring              2840.0
865237      Hamilton Gate Rd         Wanaaring              2840.0

              area_m2 contract_date settlement_date  purchase_price  \
525451   1.028000e+01    2021-05-07      2021-09-06          410000
118353   1.043000e+01    2019-07-10      2019-09-19         1880000
1176104  1.060000e+01    2024-05-01      2024-11-29           55000
795420   1.100000e+01    2022-12-02      2022-12-19           20000
167218   1.100000e+01    2019-10-31      2019-12-12          121000
...               ...           ...             ...             ...
753007   6.795500e+08    2022-05-31      2022-09-13         5625320
93594    7.330600e+08    2019-02-04      2019-05-06         5000000
533521   7.466300e+08    2021-08-12      2021-08-31         3808350
889020   1.304260e+09    2023-02-17      2023-03-31        32284565
865237   2.703300e+09    2023-02-17      2023-03-31        66799998

        nature_of_property_description primary_purpose_normalised  \
525451                       Residence                  Residence
118353                       Residence                  Residence
1176104                      Residence                  Residence
795420                           Other                  Car space
167218                       Residence                  Residence
...                                ...                        ...
753007                           Other                      Rural
93594                            Other                      Rural
533521                           Other                      Rural
889020                       Residence                  Residence
865237                       Residence                  Residence

        dealing_number         council_name  settlement_year  \
525451        AR402815       Lake Macquarie             2021
118353        AP548105          Ku-ring-gai             2019
1176104       AU632800              Hornsby             2024
795420        AS739765                Kiama             2022
167218        AP763064        Central Coast             2019
...                ...                  ...              ...
753007        AS468932  Unincorporated Area             2022
93594         AP232437  Unincorporated Area             2019
533521        AR383809  Unincorporated Area             2021
889020        AS976587  Unincorporated Area             2023
865237        AS976582  Unincorporated Area             2023

         purchase_price_outlier  price_per_m2 estimated_area_m2
525451                    False  39883.268482        397.432146
118353                    False  180249.28092        926.500998
1176104                   False   5188.679245            19.404
795420                    False   1818.181818          7.511515
167218                    False       11000.0        108.464287
...                         ...           ...               ...
753007                     True      0.008278      23718.224078
93594                      True      0.006821      30618.474429
533521                     True      0.005101      18351.894571
889020                     True      0.024753      2612466.9998
865237                     True      0.024711     5405455.83816

[1125846 rows x 18 columns]

In [335]:
# IQR for purchase price by postcode + year
# Getting rid of the outliers so the data is fairly consistent and reliable based on price per metre square
group_cols = ["property_post_code", "settlement_year"]
df['price_per_m2']=df['price_per_m2'].astype(float)
q1 = df.groupby(group_cols)["price_per_m2"].transform(
    "quantile", 0.25
)

q3 = df.groupby(group_cols)["price_per_m2"].transform(
    "quantile", 0.75
)

iqr = q3 - q1
k = 3
lower_bound = q1 - k * iqr
upper_bound = q3 + k * iqr

# Flag outliers
df["price_per_m2_outlier"] = (
    (df["price_per_m2"] < lower_bound) |
    (df["price_per_m2"] > upper_bound)
)
# Check the outliers just in case we are throwing out useful information
df.loc[df["price_per_m2_outlier"], ['property_locality','price_per_m2','purchase_price', 'area_m2', 'property_post_code', 'settlement_year']].sort_values(
    "purchase_price",
    ascending=False
)


#df.loc[
#    df["price_per_m2_outlier"], ['area_m2', 'purchase_price', 'price_per_m2', 'property_street_name']
#]
# Most of these values seem plausible so we will keep them in the dataset

,property_locality,price_per_m2,purchase_price,area_m2,property_post_code,settlement_year
715606,Sydney,210343.974264,850000000,4041.0,2000.0,2022
1470744,North Sydney,334846.765040,590000000,1762.0,2060.0,2026
546298,Sydney,196501.358696,578500000,2944.0,2000.0,2021
19149,Sydney,158066.429419,533000000,3372.0,2000.0,2018
371947,Sydney,137199.068082,530000000,3863.0,2000.0,2020
...,...,...,...,...,...,...
138805,Sydney,0.287521,3410,11860.0,2000.0,2019
138804,Sydney,0.287521,3410,11860.0,2000.0,2019
1166922,Erskine Park,1.596934,1000,626.2,2759.0,2024
2188,Tarcutta,0.919118,1000,1088.0,2652.0,2018
882776,Stanhope Gardens,2.201673,1000,454.2,2768.0,2023

In [336]:
# Now we need a to setup a price to m2 lower bound since if a property is extremely cheap then most likely its not a real transaction
# or even if it is we want properties that is atleast 0.3 dollars per metre square

df.loc[df['price_per_m2'].astype(float)<0.3, ['property_locality','price_per_m2','purchase_price', 'area_m2', 'property_post_code', 'settlement_year']].sort_values(
    "price_per_m2",
    ascending=False
)

,property_locality,price_per_m2,purchase_price,area_m2,property_post_code,settlement_year
1055365,Carlaminda,0.299925,2350000,7835300.0,2630.0,2024
290317,Mungindi,0.299760,3500000,11676000.0,2406.0,2020
267619,Pericoe,0.299568,48500,161900.0,2550.0,2020
27286,Myrtle Park,0.299555,606000,2023000.0,2713.0,2017
151178,Camira,0.299483,220000,734600.0,2469.0,2019
...,...,...,...,...,...,...
843027,Kulwin,0.000070,15000,213880000.0,2835.0,2023
571086,Nymagee,0.000061,10584,173640000.0,2831.0,2021
1359373,Coolabah,0.000050,1226,24353400.0,2831.0,2025
236822,One Tree,0.000025,1296,50950000.0,2711.0,2020
495918,Tindarey,0.000006,1120,187970000.0,2835.0,2021

In [337]:
# Now we shall remove those rows

df = df.loc[~(df['price_per_m2'].astype(float)<0.3),:]

In [338]:
# Cleaning nature of property description

df['nature_of_property_description'].value_counts(dropna=False)

nature_of_property_description
Residence      963070
Vacant land    111253
Other           47196
Name: count, dtype: int64

In [339]:
# We can convert it to string
df['nature_of_property_description'] = df['nature_of_property_description'].astype('string')

In [340]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1121519 entries, 0 to 1508051
Data columns (total 19 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   property_id                     1121519 non-null  float64
 1   property_unit_number            185557 non-null   string
 2   property_house_number           1121519 non-null  string
 3   property_street_name            1121519 non-null  string
 4   property_locality               1121519 non-null  string
 5   property_post_code              1121519 non-null  float64
 6   area_m2                         1121519 non-null  float64
 7   contract_date                   1121519 non-null  datetime64[ns]
 8   settlement_date                 1121519 non-null  datetime64[ns]
 9   purchase_price                  1121519 non-null  int64
 10  nature_of_property_description  1121519 non-null  string
 11  primary_purpose_normalised      1121397 non-null  object
 12  dealing_number                  1121519 non-null  object
 13  council_name                    1121519 non-null  string
 14  settlement_year                 1121519 non-null  int32
 15  purchase_price_outlier          1121519 non-null  bool
 16  price_per_m2                    1121519 non-null  float64
 17  estimated_area_m2               1121519 non-null  object
 18  price_per_m2_outlier            1121519 non-null  bool
dtypes: bool(2), datetime64[ns](2), float64(4), int32(1), int64(1), object(3), string(6)
memory usage: 151.9+ MB

In [341]:
# Cleaning primary purpose column by renaming it and converting it to string
df.rename(columns={"primary_purpose_normalised": "primary_purpose"}, inplace=True)
df['primary_purpose'] = df['primary_purpose'].astype('string')

In [342]:
df['primary_purpose'].value_counts(dropna=False)

primary_purpose
Residence       963149
Vacant land     111293
Commercial       27230
Rural            12605
Industrial        6513
Car space          414
Unclassified       193
<NA>               122
Name: count, dtype: Int64

In [343]:
# Filling these na rows with Unknown
df['primary_purpose']= df['primary_purpose'].fillna('Unknown')

In [344]:
df['primary_purpose'].value_counts(dropna=False)

primary_purpose
Residence       963149
Vacant land     111293
Commercial       27230
Rural            12605
Industrial        6513
Car space          414
Unclassified       193
Unknown            122
Name: count, dtype: Int64

In [345]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1121519 entries, 0 to 1508051
Data columns (total 19 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   property_id                     1121519 non-null  float64
 1   property_unit_number            185557 non-null   string
 2   property_house_number           1121519 non-null  string
 3   property_street_name            1121519 non-null  string
 4   property_locality               1121519 non-null  string
 5   property_post_code              1121519 non-null  float64
 6   area_m2                         1121519 non-null  float64
 7   contract_date                   1121519 non-null  datetime64[ns]
 8   settlement_date                 1121519 non-null  datetime64[ns]
 9   purchase_price                  1121519 non-null  int64
 10  nature_of_property_description  1121519 non-null  string
 11  primary_purpose                 1121519 non-null  string
 12  dealing_number                  1121519 non-null  object
 13  council_name                    1121519 non-null  string
 14  settlement_year                 1121519 non-null  int32
 15  purchase_price_outlier          1121519 non-null  bool
 16  price_per_m2                    1121519 non-null  float64
 17  estimated_area_m2               1121519 non-null  object
 18  price_per_m2_outlier            1121519 non-null  bool
dtypes: bool(2), datetime64[ns](2), float64(4), int32(1), int64(1), object(2), string(7)
memory usage: 151.9+ MB

In [346]:
# Cleaning dealing number

df['dealing_number'].isna().sum()

np.int64(0)

In [347]:
df['dealing_number'] = df['dealing_number'].astype('string')

In [348]:
# Now dropping all the unnecessary columns that were created just to support the cleaning of data
df = df.drop(columns=['settlement_year', 'purchase_price_outlier', 'price_per_m2', 'estimated_area_m2', 'price_per_m2_outlier'])

In [349]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1121519 entries, 0 to 1508051
Data columns (total 14 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   property_id                     1121519 non-null  float64
 1   property_unit_number            185557 non-null   string
 2   property_house_number           1121519 non-null  string
 3   property_street_name            1121519 non-null  string
 4   property_locality               1121519 non-null  string
 5   property_post_code              1121519 non-null  float64
 6   area_m2                         1121519 non-null  float64
 7   contract_date                   1121519 non-null  datetime64[ns]
 8   settlement_date                 1121519 non-null  datetime64[ns]
 9   purchase_price                  1121519 non-null  int64
 10  nature_of_property_description  1121519 non-null  string
 11  primary_purpose                 1121519 non-null  string
 12  dealing_number                  1121519 non-null  string
 13  council_name                    1121519 non-null  string
dtypes: datetime64[ns](2), float64(3), int64(1), string(8)
memory usage: 128.3 MB

In [350]:
df['contract_date'].isnull().sum()

np.int64(0)

In [353]:
# Sending all this cleaned data to the AzureSqlEdge running on Docker
# Format and URL-encode the connection attributes
from sqlalchemy import create_engine, text

# Dialect changes to mssql+pymssql
# Syntax: mssql+pymssql://username:password@hostname:port/database
connection_url = "mssql+pymssql://SA:Ajith1234@localhost:1433/nsw_property_sales"

engine = create_engine(connection_url)

with engine.connect() as connection:
    result = connection.execute(text("SELECT @@VERSION;"))
    print("Connected successfully:", result.scalar())
    table_name="nsw_property"
    df.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data successfully loaded in table ", table_name, " database nsw_property_sales")

Connected successfully: Microsoft Azure SQL Edge Developer (RTM) - 15.0.2000.1574 (ARM64)
	Jan 25 2023 10:36:08
	Copyright (C) 2019 Microsoft Corporation
	Linux (Ubuntu 18.04.6 LTS aarch64) <ARM64>
Data successfully loaded in table  nsw_property  database nsw_property_sales

In [354]:
df.to_csv("clean_nsw_property_sales.csv", index=False)

In [355]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1121519 entries, 0 to 1508051
Data columns (total 14 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   property_id                     1121519 non-null  float64
 1   property_unit_number            185557 non-null   string
 2   property_house_number           1121519 non-null  string
 3   property_street_name            1121519 non-null  string
 4   property_locality               1121519 non-null  string
 5   property_post_code              1121519 non-null  float64
 6   area_m2                         1121519 non-null  float64
 7   contract_date                   1121519 non-null  datetime64[ns]
 8   settlement_date                 1121519 non-null  datetime64[ns]
 9   purchase_price                  1121519 non-null  int64
 10  nature_of_property_description  1121519 non-null  string
 11  primary_purpose                 1121519 non-null  string
 12  dealing_number                  1121519 non-null  string
 13  council_name                    1121519 non-null  string
dtypes: datetime64[ns](2), float64(3), int64(1), string(8)
memory usage: 128.3 MB